New section describing results
qsimulate/QSP_Materials_Documenation pull request #27
Opened 2022-03-14 05:00 UTC by DrDap

New manual section describing Batch Results.

* Tested using Make html
* Figures in line
* Figures given descriptive names
* Figures in media subdirectory
* Replaces multiple sections of original manual
* Last figure is placeholder and needs to be replaced with one from GUI
* Section describing colors of conformer boxes needs to be updated

2022-03-14 15:54 UTC, spheex commented on source/batch_results/batch_results.rst
> +your calculation. The information in this section is continually updated
Since when we hit the "Status" button in the top panel, shouldn't we call this section "Batch Status"?

2022-03-14 16:58 UTC, spheex commented on source/batch_results/batch_results.rst
> +    quasi-Newton Broyden–Fletcher–Goldfarb–Shanno approach starting with
we need a proper reference, and also for the quasi Newton-Raphson method with the TRIC coordinates (Wang & Song, JCP, 2016) below

2022-03-15 18:15 UTC, DrDap commented on source/batch_results/batch_results.rst
> +your calculation. The information in this section is continually updated
The way the GUI is currently implemented the results appear as a subsection of the Details of Batch section. 

I agree that it probably makes more sense to rename Details of Batch to something like Batch Input Control and to remove the results into its own group of Batch Status. But that's not how the page is currently set up.

2022-03-15 18:20 UTC, DrDap commented on source/batch_results/batch_results.rst
> +    quasi-Newton Broyden–Fletcher–Goldfarb–Shanno approach starting with
OK, what's the reference for the MM function we use?

2022-03-15 19:30 UTC, DrDap commented on source/batch_results/batch_results.rst
> +    quasi-Newton Broyden–Fletcher–Goldfarb–Shanno approach starting with
@Samthos : Do you have a reference for the MM method/FF we are using?

2022-03-15 19:34 UTC, Samthos commented on source/batch_results/batch_results.rst
> +    quasi-Newton Broyden–Fletcher–Goldfarb–Shanno approach starting with
UFF is run from rdkit do whatever their reference is. 

GFnFF is being run with [xtb](https://xtb-docs.readthedocs.io/en/latest/contents.html)

2022-03-15 19:57 UTC, DrDap commented on source/batch_results/batch_results.rst
> +    quasi-Newton Broyden–Fletcher–Goldfarb–Shanno approach starting with
Thanks. Will update MM section with standard UFF reference and call out to RDKIT's implementation.

2022-03-16 07:45 UTC, spheex requested changes
In previous pages, I've referenced papers by using a number between square brackets, and put the complete information at the bottom of the page (+ clickable link to the original paper).
I'm going to modify this for consistency.

2022-03-16 14:09 UTC, DrDap commented on source/batch_results/batch_results.rst
> +    [:ref:`1 <MM_minimizer>`] starting with the “Conf” coordinates, and using a
We'll integrate this branch into Mail and then address this more fully.

2022-03-16 14:09 UTC, merged