added acknowledgement page
qsimulate/QSP_Materials_Documenation pull request #33
Opened 2022-03-16 17:35 UTC by spheex

I added the softwares I know that were used, but I do not know how this page should be organized. @DrDap 
And if other softwares were used? @Samthos

2022-03-16 17:39 UTC, Samthos requested changes
We also use pygsm and geometric.

2022-03-16 17:39 UTC, Samthos commented on source/acknowledgement/acknowledgement.rst
> +-  Crest
No crest right now

2022-03-17 08:38 UTC, spheex commented
Should we mention AWS as the Cloud provider in the Acknowledgement?

2022-03-17 13:59 UTC, Samthos commented
@DrDap? This get's into companies acknowledging companies. I know that can be blocked sometimes.

2022-03-17 15:37 UTC, merged