Doping panel documentation added
qsimulate/QSP_Materials_Documenation pull request #4
Opened 2022-03-08 21:31 UTC by DrDap

First pass doping panel documentation. Note that figures are included to provide an idea, but are taken from a mockup and will need to be replaced when panel is implanted on the front end.

Changes are encapsulated in the source/doping directory, consisting of a .rst documentation file and figures in the doping/media subdirectory. 

Only one other change: added a line in source/index.rst to point to the new doping documentation. 

Tested by a make HTML command in the root directory, which created the documentation as expected.

2022-03-08 21:36 UTC, Samthos commented on source/doping/doping.rst
> +replacement of one atom or small molecule type by a second atom in a
Doesn't handle small molecules

2022-03-08 21:50 UTC, Samthos requested changes

2022-03-08 21:50 UTC, Samthos commented on source/doping/doping.rst
> +replacement of one atom or small molecule type by a second atom in a
atoms can only be replaced with other atoms ATM.

2022-03-08 21:50 UTC, Samthos commented on source/doping/doping.rst
> +-  Define the amount of configurational sampling for each mole fraction
atat produces a single configuration. They are called special quasirandom structures. Ask Jia for details.

2022-03-08 21:50 UTC, Samthos commented on source/doping/doping.rst
> +-  Define the amount of configurational sampling for each mole fraction
Also, we need a section somewhere to disclose/cite the software we use. ATAT is creative commons with no modification and require atribution.

2022-03-08 21:50 UTC, Samthos commented on source/doping/doping.rst
> +unit cells are supported.
We might actually be able to handle non-rectangular unit cells. Again confirm with Jia

2022-03-08 21:50 UTC, Samthos commented on source/doping/doping.rst
> +   mole fraction)
These values will be rounded to the nearest hundredth at runtime to prevent overly large cells from being generated.

2022-03-08 21:50 UTC, Samthos commented on source/doping/doping.rst
> +min+N\*inc, max), where N = the integer part of
right now, max is only included if it's actually accessible from inc. We are using an actual Fraction for this so no worry about precision error.

2022-03-08 21:50 UTC, Samthos commented on source/doping/doping.rst
> +
DFT

2022-03-09 03:20 UTC, DrDap commented on source/doping/doping.rst
> +-  Define the amount of configurational sampling for each mole fraction
Stuff like that (ATAT is creative commons and anything else like that should probably go at the end of the manual in an attributions section. Or else in a preamble after the first page.

2022-03-09 22:37 UTC, Samthos commented on source/doping/doping.rst
> +-  Define the amount of configurational sampling for each mole fraction
I like a bulk dump somewhere near the end of the documentation. Probably a chapter with sections for attribution, citations, etc?

2022-03-09 22:38 UTC, Samthos approved these changes

2022-03-09 22:39 UTC, merged